on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs: 
  # This workflow contains a single job called "build" 
  unit_tets:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        # Execute unit tests
      - name: run unit tests
        working-directory: ./app/src/
        run: chmod +x ./test
