name: Find Latest Releases Branch

on:
  workflow_dispatch:

jobs:
  find-releases-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all branches
        run: git fetch --all

      - name: Check for newest "releases*" branch not older than 3 days
        id: find_latest_release_branch
        run: |
          RELEASE_BRANCHES=$(git for-each-ref --sort=-committerdate --format='%(refname:short)' refs/remotes/origin/releases*)

          if [ -z "$RELEASE_BRANCHES" ]; then
            echo "No branches starting with 'releases' were found."
            exit 1
          fi

          for BRANCH in $RELEASE_BRANCHES; do
            BRANCH_NAME=$(echo "$BRANCH" | sed 's|origin/||')
            COMMIT_DATE=$(git log -1 --format="%ct" "origin/$BRANCH_NAME")
            NOW=$(date +%s)
            AGE=$(( (NOW - COMMIT_DATE) / 86400 ))

            echo "Branch '$BRANCH_NAME' is $AGE day(s) old."

            if [ "$AGE" -le 3 ]; then
              echo "Using branch '$BRANCH_NAME' as the latest recent releases branch."
              echo "LATEST_RELEASE_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
              exit 0
            fi
          done

          echo "No recent release branch found (within 3 days)."
          exit 1

      - name: Print the latest release branch
        if: env.LATEST_RELEASE_BRANCH != ''
        run: echo "Latest recent release branch is ${{ env.LATEST_RELEASE_BRANCH }}"
