on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs: 
  # This workflow contains a single job called "build" 
  build: 
    # The type of runner that the job will run on 
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job 
    steps:
      - uses: actions/checkout@v3
      # Setup JAVA
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: pwd
        run: pwd
      - name: ls
        run: ls -alrth
      - name: add permisiion to gradlew
        run: chmod +x ./gradlew 
        # Execute unit tests
      - name: add permisiion to gradlew
        working-directory: ./app
        run: chmod +x ./test
