name: Pull Request Check

on:
  pull_request:

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch master branch
        run: |
          BASE=$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }})
          echo "Merge base: $BASE"
          git diff --name-only $BASE ${{ github.event.pull_request.head.sha }} > changes.txt
          cat changes.txt

      - name: Display changes
        run: |
           cat changes.txt
