name: Pull Request Check

on:
  pull_request:

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch master branch
        run: |
          echo "Fetching base branch: ${{ github.event.pull_request.base.ref }}"
          git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
          BASE=$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }})
          echo "Merge base: $BASE"
          git diff $BASE...HEAD > changes.txt

      - name: Display changes
        run: |
           cat changes.txt
