name: Pull Request Check

on:
  pull_request:

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch master branch
        run: |
          git fetch --no-tags --depth=1 origin +refs/heads/${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }} 2>&1 | tee fetch.log
          BASE=$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }})
          echo "Merge base: $BASE"
          git diff --name-only $BASE HEAD > changes.txt

      - name: Display changes
        run: |
           cat changes.txt
