name: Pull Request Check

on:
  pull_request:

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Calcualte diff
        run: |
          git fetch origin master
          BASE=$(git merge-base HEAD origin/master)
          echo "Changed files (from merge-base $BASE to HEAD):"
          git diff --name-only $BASE HEAD > changes.txt

      - name: Display changes
        run: |
          echo "--- Changed files ---"
          cat changes.txt

      - name: Set JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Change wrapper
        run: chmod +x ./gradlew

      - name: Verify Test methods are present
        shell: sh 
        run: ./gradlew :app:verifyTestMethods
