name: Pull Request Check

on:
  pull_request:

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch master branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }}
          BASE=$(git merge-base HEAD ${{ github.event.pull_request.base.sha }})
          echo "Merge base: $BASE"
          git diff $BASE...HEAD > changes.txt

      - name: Display changes
        run: |
           cat changes.txt
